# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 08 Jun 2022 17:10:56 +0000
*               @ALL          1
*               @user         8
