<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 09 Jun 2022 12:19:48 -0700
 */

$conf['title'] = 'Radahn';
$conf['template'] = 'bootstrap3';
$conf['tagline'] = 'The Starscourge Wiki';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['defer_js'] = 0;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
