# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 08 Jun 2022 17:10:56 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$PnvDPkJ334ry6nPk5Lx4LOQqEM17c8zCzletB3JbRquZjbIu9HCUi:General Radahn:justn@devsec.ca:admin,user
